# Regresión lineal multivariable: Función de coste
M2U2 - Ejercicio 1

## ¿Qué vamos a hacer?
- Implementar la función de coste para regresión lineal multivariable

Recuerda seguir las instrucciones para las entregas de prácticas indicadas en [Instrucciones entregas](https://github.com/Tokio-School/Machine-Learning/blob/main/Instrucciones%20entregas.md).

In [1]:
import numpy as np

## Tarea 1: Implementar la función de coste para regresión lineal multivariable no vectorizada

En esta tarea, debes implementar la función de coste para regresión lineal multivariable en Python. La función de coste debe seguir la función incluida en las diapositvas y en el manual del curso.

Para ello, primero rellena el código de la siguiente celda para implementar la función de coste no vectorizada.

Las diferencias entre una implementación vectorizada y no vectorizada son las siguientes:
- La vectorizada utiliza operaciones de álgebra lineal, de operaciones entre vectores/matrices.
- La no vectorizada se implementa con bucles de control for en Python, iterando entre las secuencias/listas de elementos uno a uno.
- La vectorizada utiliza Numpy, sus arrays ndarray y operaciones como np.matmul().
- La no vectorizada es menos eficiente, ya que no utiliza los métodos numéricos de Numpy sobre operaciones de C++.
- Sin embargo, la no vectorizada es bastante más sencilla de comprender en un primer momento, al ser Python puro, sin depender de otras funciones y dimensiones de vectores.

Recuerda la ecuación:

$$Y = h_\Theta(X) = X \times \Theta^T$$

$$J_\theta = \frac{1}{2m} \sum_{i = 0}^{m} (h_\theta(x^i) - y^i)^2$$

Para implementarla, sigue estos pasos:
1. Tómate un tiempo para revisar la ecuación y asegúrate que comprendes todas las operaciones matemáticas reflejadas en ella
1. Vuelve a ejercicios anteriores o revisa las diapositivas y anota en una hoja de papel (o celda auxiliar) las dimensiones de cada vector o matriz de la ecuación
1. Anota en dicho papel o celda auxiliar las operaciones de álgebra lineal paso a paso
    1. Comienza por sustituir $h_{\theta}$ en la 2ª ecuación por su valor de la 1ª
    1. La primera operación es hallar la $h_{\theta}$ o Y predicha para cada fila de X (multiplicándola por $\Theta$)
    1. La 2ª, restarle el valor de Y para dicho ejemplo/fila de X, hayando su residuo
    1. Luego elevar al cuadrado el resultado
    1. A continuación, sumar todos los cuadrados de los residuos para todos los ejemplos/filas de X
    1. Por último, dividirlos por 2 * m
1. Anota al lado de cada paso las dimensiones que debería tener su resultado. Recuerda que el resultado final de la función de coste es un escalar o número
1. Por último, piensa cómo iterar con bucles for por cada valor de X, $\Theta$ e Y para implementar la función de coste:
    1. Implementa la fórmula usando únicamente bucles for y la función sum() de la librería estándar de Python, sin usar métodos ni operadores de Numpy
    1. Itera por todas las filas o ejemplos de X (m filas)
    1. Dentro de dicho bucle, itera por las características o valores de X y $\Theta$ para calcular la Y predicha para dicho ejemplo
    1. Una vez hallados todos los residuos, halla el coste total

*Notas:*
- Los pasos mencionados son sólo una guía, una ayuda. En cada ejercicio, implementa tu código a tu manera, con el planteamiento que prefieras, utilizando el esquema de código de la celda o no
- No te preocupes demasiado por ahora por saber si funciona correctamente o no, puesto que en la siguiente tarea la comprobaremos. Si hubiera algún error, puedes volver a esta celda para corregir tu código.

In [9]:
# TODO: Implementa la función de coste no vectorizada siguiendo la siguiente plantilla

'''  Computa la función de coste para el dataset y coeficientes considerados.
    Argumentos posicionales:
    x -- array 2D de Numpy con los valores de las variables independientes de los ejemplos, de tamaño m x n
    y -- array 1D de Numpy con la variable dependiente/objetivo, de tamaño m x 1
    theta -- array 1D de Numpy con los pesos de los coeficientes del modelo, de tamaño 1 x n (vector fila)

    Devuelve:
    j -- float con el coste para dicho array theta'''


def cost_function_non_vectorized(x, y, theta):
  m = len(y) # m es el numero de ejemplos en el conjunto de datos
  j = 0 # inicializamos el coste

# Vamos a iterar por cada ejemplo (fila de X)
  for i in range(m):
    prediccion = 0 # inicializamos la predicción para el ejemplo i
    for j in range(len(theta)): # iteramos por cada característica (columna de X)
      prediccion += x[i][j] * theta[j] # multiplicamos x[i][j] por theta[j] y sumamos a la predicción

    residuo = prediccion - y[i] # residuo: diferencia entre predicción y valor real
    j += residuo ** 2 # sumamos el cuadrado del residuo

# Dividimos por 2 * m para obtener el coste final
  j= j / (2 * m)

  return j

## Tarea 2: Comprueba tu implementación

Para comprobar tu implementación, rescata tu código del notebook anterior acerca de datasets sintéticos para regresión lineal multivariable y utilízalos para generar un dataset en la siguiente celda:

In [14]:
# TODO: Genera un dataset sintético, con término de error, de la forma que escojas, con Numpy o Scikit-learn
# Definimos primero las dimensiones del dataset

m = 100
n = 3
e = 1.0 # aumento el ruido porque en el siguiente apartado obtenia valores muy parecidos.

# Luego, generamos X con valores aleatorios de tamaño m x n
X = 10 * np.random.rand(m, n) # he multiplicado por 10 para modificar los resultados muy pequeños y parecidos que obtenia en las theta1, 2, 3 y 4

# Definimos los valores reales de Tetha
Theta_verd = np.array([1.5, -2.0, 0.7]) #coeficientes reales

# Generaremos Y a partir de los valores reales de Theta y añadiremos un termino de error
Y = X @ Theta_verd + e * np.random.randn(m) # @ es la multiplicacion matricial

# Comprueba los valores y dimensiones (forma o "shape") de los vectores
print('Theta real a estimar:')
print(Theta_verd)

print('\nPrimeras 10 filas y 5 columnas de X e Y:')
print(X[:10, :5]) # asi mostramos las 10 primeras filas y 5 columnas de X
print(Y[:10]) # Asi mostramos las 10 primeras filas de Y

print('\nDimensiones de X e Y:')
print('shape X:', X.shape)
print('shape Y:', Y.shape)

Theta real a estimar:
[ 1.5 -2.   0.7]

Primeras 10 filas y 5 columnas de X e Y:
[[4.15785142 7.67331497 2.95803845]
 [4.30865796 6.13755425 8.49075701]
 [3.17496821 5.66055958 7.40366091]
 [3.25547457 0.43576475 5.71439135]
 [6.08071977 9.84412207 5.26230349]
 [1.4091764  7.5938091  2.65514582]
 [7.93268673 9.4889933  9.46156988]
 [7.14289285 4.39832476 9.85020186]
 [4.8290541  7.86977545 9.21184286]
 [6.87753937 5.86151561 2.87050639]]
[ -5.76744285  -1.11560884  -2.70800398   9.41511661  -6.73616457
 -11.53154775  -1.95549607   7.09053276  -1.04815474  -0.03057849]

Dimensiones de X e Y:
shape X: (100, 3)
shape Y: (100,)


Ahora vamos a comprobar tu implementación de la función de coste en las siguientes celdas.

Recuerda que la función de coste representa el "error" de tu modelo, el sumatorio de los cuadrados de los resíduos del mismo.

Por ello, la función de coste tiene las siguientes características:
- No tiene unidades, por lo que no podemos saber si su valor es "demasiado alto o bajo", simplemente comparar los costes de dos modelos (conjuntos de $\Theta$) diferentes
- Tiene un valor de 0 para la $\Theta$ teóricamente óptima
- Sus valores siempre son positivos
- Tiene un valor más alto cuanto más se aleja la $\Theta$ utilizada de la $\Theta$ óptima
- Su valor crece con el cuadrado de los residuos del modelo

Por lo tanto, utiliza la siguiente celda para comprobar la implementación de tu función con diferentes $\Theta$, corrigiendo tu función si es necesario. Comprueba que:
1. Si la $\Theta$ es igual que la $\Theta_{verd}$ (obtenida al definir el dataset), el coste es 0
1. Si la $\Theta$ es distinta que la $\Theta_{verd}$, el coste es distinto a 0 y positivo
1. Cuanto más alejada está la $\Theta$ de la $\Theta_{verd}$, mayor es el coste (compruébalo con 3 $\Theta$ diferentes a $\Theta_{verd}$, en orden de menor a mayor)

*Nota:* Para ello, utiliza la misma celda, modificando sus variables varias veces.

In [15]:
#TODO: Comprueba la implementación de tu función de coste
# Theta_verd es el valor real que usamos para generar los datos
theta1 = Theta_verd    # Modifica y comprueba varios valores de theta
# theta_verd es la theta optima, que deberia dar un coste muy bajo o 0
theta2 = np.array([1.4, -2.1, 0.6]) # esta theta es cercana a theta_verd = coste bajo
theta3 = np.array([0.0, 0.0, 0.0]) # esta theta alejada de theta_verd dara un coste alto
theta4 = np.array([3.0, -4.0, 1.5]) # esta theta es la más alejada a theta_verd y nos dará el coste más alto entre todos

# Comprobamos el coste con theta1 ( recordemos que este deberia ser cercano a 0)
j1 = cost_function_non_vectorized(X, Y, theta1)
print('Coste del modelo con Theta_verd:')
print(j1)
print('Theta comprobado y Theta real:')
print(theta1)
print(Theta_verd)

# Comprobamos el coste con theta2 (este debería ser mayor que j1 pero no demasiado alto, ya que esta muy cerca)
j2 = cost_function_non_vectorized(X, Y, theta2)
print('\nCoste del modelo con theta2 (cercana a Theta_verd):')
print(j2)
print('Theta comprobado:')
print(theta2)

# Comprobamos el coste con theta3 (debería ser mucho mayor)
j3 = cost_function_non_vectorized(X, Y, theta3)
print('\nCoste del modelo con theta3 (alejada de Theta_verd):')
print(j3)
print('Theta comprobado:')
print(theta3)

# Comprobamos el coste con theta4 (debería ser el mayor valor de todos)
j4 = cost_function_non_vectorized(X, Y, theta4)
print('\nCoste del modelo con theta4 (muy alejada de Theta_verd):')
print(j4)
print('Theta comprobado:')
print(theta4)

Coste del modelo con Theta_verd:
0.011970717725143076
Theta comprobado y Theta real:
[ 1.5 -2.   0.7]
[ 1.5 -2.   0.7]

Coste del modelo con theta2 (cercana a Theta_verd):
0.021682240310496242
Theta comprobado:
[ 1.4 -2.1  0.6]

Coste del modelo con theta3 (alejada de Theta_verd):
0.11080818491005744
Theta comprobado:
[0. 0. 0.]

Coste del modelo con theta4 (muy alejada de Theta_verd):
0.06606775208825709
Theta comprobado:
[ 3.  -4.   1.5]


## Tarea 3: Vectorizar la función de coste

Ahora vamos a implementar una nueva función de coste, pero en esta ocasión vectorizada.

Una función vectorizada es aquella que se realiza en base a operaciones de álgebra lineal, en lugar de p. ej. los bucles for utilizados en la primera función, y por tanto su computación es mucho más rápida y eficiente, más aún si se realiza en GPUs o procesadores especializados.

Implementa de nuevo la función de coste, pero esta vez utilizando exclusivamente las operaciones de álgebra lineal para operar con vectores/arrays de Numpy.

Consejos:
- Comprueba las dimensiones del resultado de cada operación o paso intermedio una a una si lo necesitas
- Intenta implementar la ecuación con el mínimo número de operaciones posibles, sin bucles ni iteraciones
- Utiliza funciones como [numpy.matmul()](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) o numpy.sum().
- Utiliza ndarray.reshape() para *theta* si te da algún problema en la multiplicación matricial, para conseguir un vector ndarray 2D (n+1, 1) en lugar de un 1D (n+1,)
- Asegúrate de devolver un valor *j* float, no un ndarray 2D con 1 solo elemento. Extráelo con sus índices si es necesario.

In [16]:
# TODO: Implementa la función de coste vectorizada siguiendo la siguiente plantilla

def cost_function(x, y, theta):
    """ Computa la función de coste para el dataset y coeficientes considerados.

    Argumentos posicionales:
    x -- array 2D de Numpy con los valores de las variables independientes de los ejemplos, de tamaño m x n
    y -- array 1D de Numpy con la variable dependiente/objetivo, de tamaño m x 1
    theta -- array 1D de Numpy con los pesos de los coeficientes del modelo, de tamaño 1 x n (vector fila)

    Devuelve:
    j -- float con el coste para dicho array theta
    """
    m = y.shape[0] # m es el numero de ejemplos

    # Computa la prediccion de h_theta(x)
    # theta.T @ x.T realiza la multiplicacion matricial
    h= np.matmul(x, theta) # m x 1

    # Computa la diferecia entre la prediccion y el valor real
    error = h - Y


    # Recuerda comprobar las dimensiones de la multiplicación matricial para hacerla correctamente
    j = (1/(2*m)) * np.sum(np.square(error))

    return j

Por último, vuelve a la tarea 2 y repite los mismos pasos para comprobar ahora tu función vectorizada.

In [19]:
# Definir valores de theta para comprobar la función de coste
theta1 = Theta_verd  # Theta real
theta2 = np.array([1.4, -2.1, 0.6])  # Theta cercana a la real
theta3 = np.array([0, 0, 0])  # Theta muy alejada de la real
theta4 = np.array([3.0, -4.0, 1.5])  # Theta más alejada de la real

# Calcular los costes para cada conjunto de theta
j1 = cost_function(X, Y, theta1)
j2 = cost_function(X, Y, theta2)
j3 = cost_function(X, Y, theta3)
j4 = cost_function(X, Y, theta4)

# Imprimir los resultados
print('Coste del modelo con Theta_verd:')
print(j1)
print('Theta comprobado y Theta real:')
print(theta1)
print(Theta_verd)

print('\nCoste del modelo con theta2 (cercana a Theta_verd):')
print(j2)
print('Theta comprobado:')
print(theta2)

print('\nCoste del modelo con theta3 (alejada de Theta_verd):')
print(j3)
print('Theta comprobado:')
print(theta3)

print('\nCoste del modelo con theta4 (muy alejada de Theta_verd):')
print(j4)
print('Theta comprobado:')
print(theta4)


Coste del modelo con Theta_verd:
0.4504781714922579
Theta comprobado y Theta real:
[ 1.5 -2.   0.7]
[ 1.5 -2.   0.7]

Coste del modelo con theta2 (cercana a Theta_verd):
1.619212180252749
Theta comprobado:
[ 1.4 -2.1  0.6]

Coste del modelo con theta3 (alejada de Theta_verd):
27.082475989098725
Theta comprobado:
[0 0 0]

Coste del modelo con theta4 (muy alejada de Theta_verd):
32.490613852199665
Theta comprobado:
[ 3.  -4.   1.5]
